name: Auto merge Owner's changes

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - master

jobs:
  approve:
    if: github.actor == github.repository.owner
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v3
      - name: approve pull pull_request
        uses: hmarr/auto-approve-action@v3.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          review-message: "Auto approved automated PR"
  merge:
    needs: [approve]
    runs-on: ubuntu-latest
    steps:
      - name: merge 
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
