name: pull_request

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: print success message
        run: echo "Success!"

