name: Tests runner

on:
  push:
    branches:
      - 05-02-pull-requests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: test
        run: node example.js
  create-pull-request:
    needs: [test]
    permissions: write-all
    if: github.actor == 'dan-almenar'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: make new PR
        uses: repo-sync/pull-request@v2.12.1
        with:
          pr_label: automerge
