name: Action wit artifacts

on:
  push:
    branches:
      - 04-01-artifacts

jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: set up Go env
        uses: actions/setup-go@v4.0.0
      - name: build binary
        run: go build main.go
      - name: upload binary 
        uses: actions/upload-artifact@v3.1.2
        with:
          name: hello
          path: ./main
  runner:
    runs-on: ubuntu-latest
    needs: [builder]
    steps:
      - name: download binary
        uses: actions/download-artifact@v2.1.1
        with:
          name: hello
      - name: run binary
        run: ./hello
